### ISSUE TITLE
How to find a key in ObservableDictionary<number, IPhone)

### ISSUE THREAD

**Issue by st-clair-clarke** [slavik57/eyepatch#22]
Hi,
Given an instance of the dictionary

`$dictionary = ObservableDictionary<number, IPhone)`

I try to find the key with the following

`var foundKey = $dictionary.findKey(2);`

but it will not accept the integer as key.

What is the correct method?

Thanks

**Comment by slavik57** [comment]
If you look at the d.ts file you will see that `findKey()` accepts a predicate, which is a function that receives a key and returns a boolean, whether the key is found or not. What it actually does it iterates over the keys and returns the key for which the predicate returns true.
So using `findKey()` would be like this: `$dictionary.findKey(_key => _key === 2)`

For **value types** (string/number/boolean) you can work with the dictionary like you are used to with:
`$dictionary.delete(2);`
`$dictionary.containsKey(2);`
`$dictionary.getValueByKey(2);`
It only works for value types since for them the dictionary can't alter their properties so it uses their value as an ID for the dictionaries internal data structures.
